development:
  db_database: tp
  db_username: postgres
  db_password: deathstrike28
  db_host: localhost
  db_port: '5432'

production:
  db_database: tp
  db_username: postgres
  db_password: deathstrike28
  db_host: localhost
  db_port: '5432'

test:
  db_database: tp
  db_username: postgres
  db_password: deathstrike28
  db_host: localhost
  db_port: '5432'